name: 'Create a .env file'
description: 'Create a .env file'
branding:
  icon: 'box'
  color: 'orange'
author: 'https://github.com/DeveloperRic'
inputs:
  full_text:
    required: true
    description: 'Text to be dumped in the .env file (the text will be trimmed). Any existing file will be overwritten.'
  directory:
    description: 'Directory to write the file to (defaults to .). Parent directories will NOT be created.'
    default: '.'
  include_env_vars:
    required: false
    description: |
      If set, environemnt vars starting with ACTION_CREATE_ENV_ will be included (i.e. ACTION_CREATE_ENV_PROD=1 will be incldued in .env as PROD=1).
      Vars set in this way are written after <full_text>.
runs:
  using: 'node12'
  main: 'dist/index.js'
