name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test-using-default-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          full_text: |
            PROD=0
            TEST=1
  test-using-provided-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir __tests__/artifacts
      - uses: ./
        with:
          directory: __tests__/artifacts
          full_text: |
            PROD=0
            TEST=1
  test-override-existing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'PROD=0' > __tests__/artifacts/.env
      - uses: ./
        with:
          full_text: TEST=1
